[package]
name = "ifc"
version = "0.1.0"
edition.workspace = true
publish = false

[build-dependencies]
xsd-parser = { workspace = true }

[dependencies]
xsd-parser-types = { workspace = true, features = [ "quick-xml" ] }
num = { workspace = true }
