[package]
name = "read_write"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
num = "0.4.3"
xsd-parser-types = { workspace = true, features = [ "quick-xml" ] }

[build-dependencies]
xsd-parser = { workspace = true }
